services:
  - type: web
    name: adv-voice
    env: python
    buildCommand: |
      pip install -U pip
      pip install -r requirements.txt
    startCommand: python -m gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000